// <auto-generated />
using System;
using Analytics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analytics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260928132242_BookingLog")]
    partial class BookingLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analytics.Infrastructure.Persistence.OwnerBooking", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("OwnerId", "BookedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_owner_bookings_owner_booked_at");

                    b.ToTable("owner_bookings", (string)null);
                });

            modelBuilder.Entity("Analytics.Infrastructure.Persistence.OwnerMonthly", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Expenses")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("expenses");

                    b.Property<decimal>("Income")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("income");

                    b.Property<int>("Transactions")
                        .HasColumnType("integer")
                        .HasColumnName("transactions");

                    b.HasKey("OwnerId", "Year", "Month", "Currency");

                    b.ToTable("owner_monthly", (string)null);
                });

            modelBuilder.Entity("Analytics.Infrastructure.Persistence.ProcessedTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("TransactionId");

                    b.ToTable("processed_transactions", (string)null);
                });

            modelBuilder.Entity("Analytics.Infrastructure.Persistence.SystemDaily", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Deposits")
                        .HasColumnType("integer")
                        .HasColumnName("deposits");

                    b.Property<int>("Transfers")
                        .HasColumnType("integer")
                        .HasColumnName("transfers");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("volume");

                    b.Property<int>("Withdrawals")
                        .HasColumnType("integer")
                        .HasColumnName("withdrawals");

                    b.HasKey("Day", "Currency");

                    b.ToTable("system_daily", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
